-- ═══════════════════════════════════════════════════════════════════════════
-- Kaushalya Developmental Screening Platform — item bank becomes sole source
--
-- 0006_item_bank.sql deliberately kept item_overrides as a diff on top of
-- content/items.ts: the shipped TypeScript file stayed the reviewable source
-- of truth, and this table only recorded what an admin changed.
--
-- That two-tier design is retired. From here on item_overrides is not a diff
-- — it is the entire question bank. content/items.ts stops being read by the
-- assessment, the scoring engine or the admin item-bank page at runtime; it
-- remains in the repo only as the historical transcription that seeded this
-- migration and as test fixture data (see tests/scoring.test.ts).
--
-- This migration inserts every question content/items.ts shipped, as a full,
-- ordinary row — not a diff entry — so nothing a parent could previously be
-- asked disappears the moment the code stops reading that file. `ON CONFLICT
-- DO NOTHING` means an id that already has a row (an admin edited or retired
-- it before this migration ran) keeps that admin's version untouched.
-- ═══════════════════════════════════════════════════════════════════════════

insert into public.item_overrides
  (id, domain, stage_id, text, how, kind, source, invert, min_age_months, choices, unit, deleted)
values
('s1-vision-01', 'vision', 's1', 'Do your child''s pupils dilate in a dark room?', 'Take them into a dark room for a minute, then look closely at the black centre of each eye; it should have grown wider.', 'yesno', 'ACE', false, null, null, null, false),
('s1-auditory-01', 'auditory', 's1', 'Does your child physically startle at any sudden or sharp sound?', 'Clap once, out of sight and about a metre away, and watch for a blink, a jerk, or a pause in movement.', 'yesno', 'ACE', false, null, null, null, false),
('s1-auditory-02', 'auditory', 's1', 'Does your child react appropriately to sudden sounds?', 'After the startle, watch whether they settle again, rather than staying distressed, or not reacting at all.', 'yesno', 'ACE', false, null, null, null, false),
('s1-tactile-01', 'tactile', 's1', 'Using your thumbnail, scratch the sole of your child''s foot from the heel to the toe. Does his big toe move downward?', 'Draw your thumbnail firmly up the sole from heel to toe, and watch what the big toe does.', 'yesno', 'ACE', false, null, null, null, false),
('s1-mobility-01', 'mobility', 's1', 'Does your child move his arms and legs freely?', 'Watch during a nappy change, look for easy, similar movement on both sides.', 'yesno', 'ACE', false, null, null, null, false),
('s1-mobility-02', 'mobility', 's1', 'Are his arms and/or legs too tight or too floppy?', 'Gently bend and straighten an arm and a leg. Feel for stiffness that resists you, or for a limb with no tone at all.', 'yesno', 'ACE', true, null, null, null, false),
('s1-language-01', 'language', 's1', 'Does he have a lusty cry?', 'When they cry from hunger or discomfort, listen for a strong, full sound rather than a weak or thin one.', 'yesno', 'ACE', false, null, null, null, false),
('s1-hand-01', 'hand', 's1', 'When you put an object or finger in the palm of your child''s hand, does he grasp it?', 'Press a finger gently into the palm and feel for a grip closing around it.', 'yesno', 'ACE', false, null, null, null, false),
('s2-vision-01', 'vision', 's2', 'Does your child follow you with his eyes as you walk across the room?', 'Walk slowly from one side of the room to the other while they are calm and awake, and watch whether their eyes come with you.', 'yesno', 'ACE', false, null, null, null, false),
('s2-vision-02', 'vision', 's2', 'Is your child aware of lights?', 'In a dim room, switch on a lamp off to one side and watch for their eyes or head turning towards it.', 'yesno', 'ACE', false, null, null, null, false),
('s2-vision-03', 'vision', 's2', 'Do your child''s pupils constrict immediately when you shine a light into his eyes?', 'In a dim room, shine a torch briefly towards one eye from the side, and watch the black centre shrink at once.', 'yesno', 'ACE', false, null, null, null, false),
('s2-auditory-01', 'auditory', 's2', 'Does your child follow or respond to loud and threatening sounds?', 'Notice what happens with a door slam, a cooker whistle or a horn; look for turning towards it, freezing, or crying.', 'yesno', 'ACE', false, null, null, null, false),
('s2-tactile-01', 'tactile', 's2', 'Does your child have an immediate response to pain in all the areas of his body?', 'Notice their reaction to ordinary knocks in different places: arms, legs, back, feet.', 'yesno', 'ACE', false, null, null, null, false),
('s2-tactile-02', 'tactile', 's2', 'Does your child have an appropriate response to hot and cold?', 'Watch how they react to a cool cloth, and to a warm bath.', 'yesno', 'ACE', false, null, null, null, false),
('s2-tactile-03', 'tactile', 's2', 'Is his response appropriate all over his body?', 'Check that no part of the body reacts noticeably less than the rest.', 'yesno', 'ACE', false, null, null, null, false),
('s2-mobility-01', 'mobility', 's2', 'Does your child crawl across the room on his tummy?', 'Put a favourite toy a few feet away on the floor and let them go for it on their tummy.', 'yesno', 'ACE', false, null, null, null, false),
('s2-mobility-02', 'mobility', 's2', 'Does your child crawl in a smooth cross pattern?', 'Watch which limbs move together: a cross pattern is right arm with left leg, then left arm with right leg.', 'yesno', 'ACE', false, null, null, null, false),
('s2-language-01', 'language', 's2', 'Does your child have a vital cry when he is in pain?', 'Notice whether the cry after a knock sounds different and more urgent than the everyday cry.', 'yesno', 'ACE', false, null, null, null, false),
('s2-language-02', 'language', 's2', 'Is his cry appropriately loud?', 'Listen from the next room; you should hear it clearly through a closed door.', 'yesno', 'ACE', false, null, null, null, false),
('s2-hand-01', 'hand', 's2', 'Does your child have the ability to let go of an object easily?', 'Once they are holding something, watch whether they can open the hand and drop it on purpose.', 'yesno', 'ACE', false, null, null, null, false),
('s2-hand-02', 'hand', 's2', 'Does he do so equally well with both hands?', 'Try the same thing again with the other hand.', 'yesno', 'ACE', false, null, null, null, false),
('s3-vision-01', 'vision', 's3', 'Does your child recognise many familiar objects?', 'Hold up things they know (a bottle, a favourite toy, a spoon), one at a time, and watch for a change in their face or for reaching.', 'yesno', 'ACE', false, null, null, null, false),
('s3-vision-02', 'vision', 's3', 'Does your child recognise your face without any sound or touch clues?', 'Come into view silently, without speaking or touching them, and watch for recognition.', 'yesno', 'ACE', false, null, null, null, false),
('s3-vision-03', 'vision', 's3', 'If you change your facial expression greatly, does your child notice?', 'Face them closely, then switch from a big smile to a surprised face, and watch whether they react.', 'yesno', 'ACE', false, null, null, null, false),
('s3-auditory-01', 'auditory', 's3', 'Does your child respond with a smile to your loving tone of voice?', 'Speak warmly and softly, face to face, then pause several seconds to let them answer.', 'yesno', 'ACE', false, null, null, null, false),
('s3-auditory-02', 'auditory', 's3', 'Does your child get upset when you speak in an angry tone of voice?', 'Say something ordinary in a sharp tone, keeping your face neutral, and watch for a change.', 'yesno', 'ACE', false, null, null, null, false),
('s3-auditory-03', 'auditory', 's3', 'Does your child react appropriately to everyday noises in the house?', 'Watch their response to the doorbell, a mixer, running water: interested rather than alarmed or blank.', 'yesno', 'ACE', false, null, null, null, false),
('s3-tactile-01', 'tactile', 's3', 'Does your child appreciate coolness and warmth appropriately?', 'Touch a cool spoon and then a warm one to their arm, and watch for two different reactions.', 'yesno', 'ACE', false, null, null, null, false),
('s3-tactile-02', 'tactile', 's3', 'Does your child enjoy being stroked?', 'Stroke their arm slowly and watch whether they settle, rather than pulling away.', 'yesno', 'ACE', false, null, null, null, false),
('s3-tactile-03', 'tactile', 's3', 'Is his response appropriate all over his body?', 'Try the same stroke on arms, legs, back and tummy, and compare.', 'yesno', 'ACE', false, null, null, null, false),
('s3-tactile-04', 'tactile', 's3', 'Does your child respond to soft touch?', 'Brush a fingertip very lightly on the back of the hand, and watch for any notice at all.', 'yesno', 'ACE', false, null, null, null, false),
('s3-mobility-01', 'mobility', 's3', 'Does your child creep across the room on his hands and knees?', 'Place a toy across the room and watch them travel to it up off the floor, on hands and knees.', 'yesno', 'ACE', false, null, null, null, false),
('s3-mobility-02', 'mobility', 's3', 'Does your child creep in a smooth cross pattern?', 'Watch for right hand with left knee, then left hand with right knee, without a hitch.', 'yesno', 'ACE', false, null, null, null, false),
('s3-language-01', 'language', 's3', 'Does your child make a variety of sounds which let you know whether he is happy, unhappy, hungry or asleep?', 'Over a day, notice whether you can tell what they want from the sound alone, without looking.', 'yesno', 'ACE', false, null, null, null, false),
('s3-language-02', 'language', 's3', 'Does he make the full range of sounds of a well seven-month-old?', 'Listen for babbling with consonants (''ba'', ''da'', ''ma'') repeated in strings, not just vowel sounds.', 'yesno', 'ACE', false, null, null, null, false),
('s3-hand-01', 'hand', 's3', 'Does your child spontaneously reach out and pick up objects?', 'Put a toy within arm''s reach and wait, without offering it; watch for them going for it themselves.', 'yesno', 'ACE', false, null, null, null, false),
('s3-hand-02', 'hand', 's3', 'Does he do so equally well with both hands?', 'Place the toy on the other side and watch whether that hand works as well.', 'yesno', 'ACE', false, null, null, null, false),
('s4-vision-01', 'vision', 's4', 'Are your child''s eyes consistently straight throughout the day?', 'Watch both eyes at different times (morning, after a nap, in the evening) and check they point the same way together.', 'yesno', 'ACE', false, null, null, null, false),
('s4-vision-02', 'vision', 's4', 'Even if your child is tired, sick or upset, do his eyes remain perfectly straight?', 'Check again at the end of a long day, or during an illness, when any drift is easiest to see.', 'yesno', 'ACE', false, null, null, null, false),
('s4-auditory-01', 'auditory', 's4', 'Does your child consistently respond to two or more words?', 'From another part of the room, say two words they know (their name, and ''milk'') and see whether each one gets a reliable response.', 'yesno', 'ACE', false, null, null, null, false),
('s4-tactile-01', 'tactile', 's4', 'Can your child feel a penny on a flat surface?', 'Place a coin on a table, guide their hand over it with their eyes closed, and see whether they find it.', 'yesno', 'ACE', false, null, null, null, false),
('s4-tactile-02', 'tactile', 's4', 'Can he do so with both hands?', 'Try the same thing again with the other hand.', 'yesno', 'ACE', false, null, null, null, false),
('s4-mobility-01', 'mobility', 's4', 'Can your child walk across a room completely independently?', 'Stand back and let them cross the room with nothing to hold and nobody within reach.', 'yesno', 'ACE', false, null, null, null, false),
('s4-mobility-02', 'mobility', 's4', 'Does your child walk across the room with his arms up in the air for balance?', 'Watch where the arms sit while they walk; at this stage they are up, at or above shoulder height.', 'yesno', 'ACE', false, null, null, null, false),
('s4-mobility-03', 'mobility', 's4', 'Does your child stand up without support?', 'From sitting on the floor, watch them get to their feet without holding furniture or a hand.', 'yesno', 'ACE', false, null, null, null, false),
('s4-language-01', 'language', 's4', 'Does your child say two or more words spontaneously and meaningfully?', 'Wait for them to use a word on their own, for the right thing, without you saying it first.', 'yesno', 'ACE', false, null, null, null, false),
('s4-language-02', 'language', 's4', 'Which words does your child say?', 'List the words you have heard them use meaningfully.', 'text', 'ACE', false, null, null, null, false),
('s4-hand-01', 'hand', 's4', 'Does your child pick up objects between his thumb and forefinger, for example picking up crumbs?', 'Scatter a few crumbs or peas on the tray and watch which fingers they use.', 'yesno', 'ACE', false, null, null, null, false),
('s4-hand-02', 'hand', 's4', 'Does he hold a pen or pencil between his thumb and two fingers?', 'Offer a pencil and paper and watch the grip, rather than what they draw.', 'yesno', 'ACE', false, null, null, null, false),
('s4-hand-03', 'hand', 's4', 'Does he do so equally well with both hands?', 'Offer the pencil to the other hand and watch the grip again.', 'yesno', 'ACE', false, null, null, null, false),
('s5-vision-01', 'vision', 's5', 'Does your child know pictures?', 'Show a picture book and ask them to point to something they know: a dog, a car, a cup.', 'yesno', 'ACE', false, null, null, null, false),
('s5-vision-02', 'vision', 's5', 'Does your child recognise traffic signals, the difference between red, amber and green?', 'At a signal, or with three coloured cards, ask which one means stop and which means go.', 'yesno', 'ACE', false, null, null, null, false),
('s5-auditory-01', 'auditory', 's5', 'Does your child understand 10 to 25 words?', 'Name familiar things one at a time without pointing, and ask them to find or look at each one.', 'yesno', 'ACE', false, null, null, null, false),
('s5-auditory-02', 'auditory', 's5', 'Which words does your child understand?', 'List the words they reliably respond to.', 'text', 'ACE', false, null, null, null, false),
('s5-auditory-03', 'auditory', 's5', 'Does your child respond to directions?', 'Give one simple instruction with no gesture (''bring me your shoe'') and see whether they act on it.', 'yesno', 'ACE', false, null, null, null, false),
('s5-auditory-04', 'auditory', 's5', 'Please give an example of a direction he follows', 'Write down one instruction they reliably act on.', 'text', 'ACE', false, null, null, null, false),
('s5-auditory-05', 'auditory', 's5', 'Does your child understand couplets of words, such as ''get up'', ''sit down'', ''blue shirt'', ''orange juice''?', 'Say a two-word phrase with no pointing, and watch whether they do the whole thing rather than just one half.', 'yesno', 'ACE', false, null, null, null, false),
('s5-tactile-01', 'tactile', 's5', 'Does your child recognise familiar objects by the way they feel?', 'With their eyes closed, put a spoon or a familiar toy in their hand and ask what it is.', 'yesno', 'ACE', false, null, null, null, false),
('s5-tactile-02', 'tactile', 's5', 'Can he do so with both hands?', 'Try the same thing again with the other hand.', 'yesno', 'ACE', false, null, null, null, false),
('s5-tactile-03', 'tactile', 's5', 'Does your child differentiate between a toy elephant and a toy horse just by touch, with his eyes closed?', 'Eyes closed, hand them one and then the other, and ask which animal each one is.', 'yesno', 'ACE', false, null, null, null, false),
('s5-mobility-01', 'mobility', 's5', 'Can your child walk across a room carrying an object?', 'Hand them a toy at one side of the room and ask them to bring it to you at the other.', 'yesno', 'ACE', false, null, null, null, false),
('s5-mobility-02', 'mobility', 's5', 'Does your child walk with his arms down?', 'Watch the arms while they walk: hanging and swinging by the sides, not held up for balance.', 'yesno', 'ACE', false, null, null, null, false),
('s5-language-01', 'language', 's5', 'Does your child say 10 to 25 words?', 'Over a few days, write down every different word you hear them use meaningfully, then count the list.', 'yesno', 'AUTHORED', false, null, null, null, false),
('s5-language-02', 'language', 's5', 'How many words does your child say?', 'Count the list of different words you have heard them use.', 'count', 'ACE', false, null, null, 'words', false),
('s5-language-03', 'language', 's5', 'Please give some examples', 'Write down a few of the words.', 'text', 'ACE', false, null, null, null, false),
('s5-language-04', 'language', 's5', 'Does your child use two words together, like “good boy” or “sit down”?', 'Listen for two words joined on purpose, rather than two separate words said one after the other.', 'yesno', 'ACE', false, null, null, null, false),
('s5-language-05', 'language', 's5', 'Please give an example', 'Write down one two-word phrase you have heard.', 'text', 'ACE', false, null, null, null, false),
('s5-hand-01', 'hand', 's5', 'Can your child pick up objects between his thumb and forefinger using both hands at the same time?', 'Put small objects on both sides and ask them to pick one up with each hand together.', 'yesno', 'ACE', false, null, null, null, false),
('s6-vision-01', 'vision', 's6', 'Does your child know letters?', 'Write a few letters they see often and ask them to name each one.', 'yesno', 'ACE', false, null, null, null, false),
('s6-vision-02', 'vision', 's6', 'Does your child know numbers?', 'Write a few numerals and ask them to name each one.', 'yesno', 'ACE', false, null, null, null, false),
('s6-auditory-01', 'auditory', 's6', 'Does your child understand at least 2,000 words?', 'Over a day, notice whether there is anything you say in ordinary conversation that they miss.', 'yesno', 'ACE', false, null, null, null, false),
('s6-auditory-02', 'auditory', 's6', 'Does he follow two or three-step instructions?', 'Ask for a chain (''pick up your cup, put it in the sink, then come here'') without repeating yourself.', 'yesno', 'ACE', false, null, null, null, false),
('s6-auditory-03', 'auditory', 's6', 'Please give an example', 'Write down one multi-step instruction they follow.', 'text', 'ACE', false, null, null, null, false),
('s6-tactile-01', 'tactile', 's6', 'Does your child determine the characteristics of objects by touch alone: hard, soft, fuzzy, sticky?', 'Eyes closed, hand them a stone, some cotton wool and sticky tape, and ask what each one feels like.', 'yesno', 'ACE', false, null, null, null, false),
('s6-tactile-02', 'tactile', 's6', 'Can he do so with both hands?', 'Try the same objects again with the other hand.', 'yesno', 'ACE', false, null, null, null, false),
('s6-mobility-01', 'mobility', 's6', 'Does your child walk in a cross pattern?', 'Watch the opposite arm swing forward with each leg as they walk.', 'yesno', 'ACE', false, null, null, null, false),
('s6-mobility-02', 'mobility', 's6', 'Does he run in a cross pattern?', 'Watch for the same opposite arm-and-leg swing while they run.', 'yesno', 'ACE', false, null, null, null, false),
('s6-mobility-03', 'mobility', 's6', 'Is his walking and running appropriate for his age?', 'Compare with other children of the same age at the park.', 'yesno', 'ACE', false, null, null, null, false),
('s6-language-01', 'language', 's6', 'Does your child say 2,000 words?', 'In practice this is a child who can say anything they want to say in everyday life without getting stuck for a word.', 'yesno', 'ACE', false, null, null, null, false),
('s6-language-02', 'language', 's6', 'What percentage of what he says can you understand?', 'Think about a normal day and estimate how much of their speech is clear to you.', 'percent', 'ACE', false, null, null, '%', false),
('s6-language-03', 'language', 's6', 'Does he speak consistently in short sentences?', 'Listen for three or more words joined with proper structure, most times they speak, not just occasionally.', 'yesno', 'ACE', false, null, null, null, false),
('s6-language-04', 'language', 's6', 'Please give an example', 'Write down one sentence you have heard them say.', 'text', 'ACE', false, null, null, null, false),
('s6-hand-01', 'hand', 's6', 'Can your child unscrew a lid from a bottle?', 'Hand them a closed bottle with a lid that turns easily, and let them work at it.', 'yesno', 'ACE', false, null, null, null, false),
('s6-hand-02', 'hand', 's6', 'Can your child pour water from a mug into a glass, holding both objects in his hands?', 'Half-fill a mug, give them an empty glass, and watch them pour with one in each hand.', 'yesno', 'ACE', false, null, null, null, false),
('s6-hand-03', 'hand', 's6', 'If yes, in which hand does he lift the heavier object?', 'Watch which hand takes the full mug and which takes the empty glass.', 'choice', 'ACE', false, null, ARRAY['Left', 'Right'], null, false),
('s7-vision-01', 'vision', 's7', 'Does your child read?', 'Give them a page they have not seen before and ask them to read it out to you.', 'yesno', 'ACE', false, null, null, null, false),
('s7-vision-02', 'vision', 's7', 'How many books can your child read?', 'Count the books they can read through on their own.', 'count', 'ACE', false, null, null, 'books', false),
('s7-vision-03', 'vision', 's7', 'How many sentences can your child read?', 'Count roughly how many written sentences they can read.', 'count', 'ACE', false, null, null, 'sentences', false),
('s7-vision-04', 'vision', 's7', 'How many phrases can your child read?', 'Count roughly how many written phrases they can read.', 'count', 'ACE', false, null, null, 'phrases', false),
('s7-vision-05', 'vision', 's7', 'How many words can your child read?', 'Count roughly how many written words they can read.', 'count', 'ACE', false, null, null, 'words', false),
('s7-vision-06', 'vision', 's7', 'Does your child read at his age level?', 'Compare with a school reader written for their year.', 'yesno', 'ACE', false, 72, null, null, false),
('s7-auditory-01', 'auditory', 's7', 'Does your child understand all of the vocabulary in his everyday environment, as well as an average six-year-old?', 'Listen to a normal adult conversation around them and see whether they follow it without asking what words mean.', 'yesno', 'ACE', false, null, null, null, false),
('s7-auditory-02', 'auditory', 's7', 'Does your child understand at his age level?', 'Compare with what other children in their school year are expected to follow.', 'yesno', 'ACE', false, 72, null, null, false),
('s7-tactile-01', 'tactile', 's7', 'Can your child tell the “head” from the tail of a coin by touch alone?', 'Eyes closed, place a coin in their hand and ask which side is facing up.', 'yesno', 'ACE', false, null, null, null, false),
('s7-tactile-02', 'tactile', 's7', 'Can he do so with both hands?', 'Try the same coin again in the other hand.', 'yesno', 'ACE', false, null, null, null, false),
('s7-mobility-01', 'mobility', 's7', 'Can your child balance on one foot?', 'Ask them to stand on one leg and count; several seconds without putting the other foot down.', 'yesno', 'ACE', false, null, null, null, false),
('s7-mobility-02', 'mobility', 's7', 'Which foot does he prefer?', 'Note which leg they stand on without being told.', 'choice', 'ACE', false, null, ARRAY['Left', 'Right'], null, false),
('s7-mobility-03', 'mobility', 's7', 'Can your child kick a ball?', 'Roll a ball gently towards them and ask them to kick it back.', 'yesno', 'ACE', false, null, null, null, false),
('s7-mobility-04', 'mobility', 's7', 'Which foot does he prefer to kick with?', 'Note which foot they use without being told.', 'choice', 'ACE', false, null, ARRAY['Left', 'Right'], null, false),
('s7-mobility-05', 'mobility', 's7', 'Is his coordination appropriate for his age?', 'Compare with other children in their school year at running, climbing and ball games.', 'yesno', 'ACE', false, 72, null, null, false),
('s7-language-01', 'language', 's7', 'Does your child speak as well as an average six-year-old?', 'Ask them to explain something that happened; listen for a full account, in order, that a stranger would follow.', 'yesno', 'ACE', false, null, null, null, false),
('s7-language-02', 'language', 's7', 'Does your child speak at his age level?', 'Compare with other children in their school year.', 'yesno', 'ACE', false, 72, null, null, false),
('s7-hand-01', 'hand', 's7', 'Does your child write independently?', 'Ask them to write something of their own, without copying and without being told the spelling.', 'yesno', 'ACE', false, null, null, null, false),
('s7-hand-02', 'hand', 's7', 'How many words can he write?', 'Count roughly how many words they can write unaided.', 'count', 'ACE', false, null, null, 'words', false),
('s7-hand-03', 'hand', 's7', 'Can he write in sentences?', 'Ask them to write about something that happened today, and look for full sentences.', 'yesno', 'ACE', false, null, null, null, false),
('s7-hand-04', 'hand', 's7', 'With which hand does he write?', 'Note which hand they pick the pencil up with.', 'choice', 'ACE', false, null, ARRAY['Left', 'Right'], null, false),
('s7-hand-05', 'hand', 's7', 'Is his writing equal to other kids his age?', 'Compare with the written work of other children in their school year.', 'yesno', 'ACE', false, 72, null, null, false)
on conflict (id) do nothing;
